services:
  redis:
    image: redis:4
    expose:
      - "6379"

  app:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
    ports:
      - 8000
    volumes:
      - .:/srv/app
    depends_on:
      - redis
    command:
      ["poetry", "run", "gunicorn", "-b", "0.0.0.0", "app:app"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"

networks:
  default:
    driver: bridge
    name: app
